site_name: SpELL
repo_name: bramvrancken/SpELL-ULB.github.io
repo_url: https://github.com/bramvrancken/SpELL-ULB.github.io
site_url: https://spell-ulb.github.io/

nav:
    - Home: index.md
    #- Recently edited:
    #      - bioconda.md
    #      - colors.md
    #      - leuven-bars.md
    #      - leuven-cafes.md
    #     - beagle-instll-hpc.md
    #      - singularity.md
    - Practical:
          - upon-arrival-in-Brussels.md
          - ordering-office-supplies.md
    - Social:
        - leuven-bars.md
        - leuven-cafes.md
        - leuven-restaurants.md
        - Signal.md
    - Grants: 
        - fwo-application.md
        - fnrs-application.md
    - PhD - practical:
        - phd-timeline.md
    - Phylogenetics: 
        - intro-to-phylogenetics.md
        - maximum-likelihood-phylogenetics.md
        - bayesian-phylogenetics.md
        - how-to-read-a-tree.md
        - coalescent.md
        - phylogeography.md
        - plotting-trees.md
    - Software and hardware:
        - CECI-and-other-clusters.md
        - software-microsoft-office-license.md
        - running-beast.md
        - beagle-instll-hpc.md
        - beagle-instll-local.md
        - bioconda.md
        - docker.md
        - github-primer.md
        - log-combiner.md
        - singularity.md
        - tempest.md
        - tracer.md
        - tree-annotator.md
    - Scientific good practises:
        - colors.md

theme:
    name: material
    font:
        text: Merriweather Sans
        code: Red Hat Mono
    # favicon: image that appears in tab    
    favicon: images/spell-logo_grey_noText.png
    logo: images/spell-logo_grey_noText.png
    palette:
#        # system preference
#        - media: "(prefers-color-scheme)"
#          toggle:
#              icon: material/brightness-auto
#              name: Switch to light mode
        # light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        # dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
              icon: material/weather-night
              name: Switch to system preference
    font:
        text: "Lora"
        code: "Ubuntu Mono"    
    features:
        - announce.dismiss
        - content.action.edit
        - content.code.annotate
        - content.code.copy
        - navigation.sections
        - navigation.prune
        - navigation.top
        - navigation.tracking
        - search.share
        - search.suggest
        - search.highlight
        - toc.follow
        #- navigation.footer

extra_css:
    - stylesheets/extra.css
    - https://unpkg.com/leaflet@1.3.1/dist/leaflet.css
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css

extra_javascript:
    - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
    - js/map-renderer.js

markdown_extensions:
    # highlights of text in boxes (tripple !!! of ???)
    - admonition
    - attr_list
    - def_list
    - tables
    - md_in_html
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.critic
    - pymdownx.snippets
    # for diagrams: 
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.details
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.arithmatex:
          generic: true

plugins:
    - search
    - git-authors:
          show_contribution: true
          sort_authors_by: contribution
          ignore_authors:
              - 61584065+joon-klaps@users.noreply.github.com
          exclude:
              - index.md
    - git-revision-date-localized:
          type: timeago
    - awesome-pages

extra:
    homepage: https://spell.ulb.be/
    generator: false
    social:
        #- icon: fontawesome/brands/x-twitter
        #  link: https://twitter.com/LemeyLab
        - icon: fontawesome/brands/github
          link: https://github.com/bramvrancken
