site_name: SpELL
repo_name: bramvrancken/SpELL-ULB.github.io
repo_url: https://github.com/bramvrancken/SpELL-ULB.github.io
site_url: https://spell-ulb.github.io/

nav:
    - Home: index.md
    #- Recently edited:
    #      - bioconda.md
    #      - colors.md
    #      - leuven-bars.md
    #      - leuven-cafes.md
    #     - beagle-instll-hpc.md
    #      - singularity.md
    - Practical:
          - practical/upon-arrival-in-Brussels.md
          - practical/ordering-office-supplies.md
          - practical/admin-assitance.md
    - Social:
        - social/brussels-horeca.md
        - social/leuven-horeca.md
        - social/messenger-group.md
    - Grants: 
        - grants/fnrs-fwo-application.md
    - PhD - practical:
        - PhD-practical/phd-timeline.md
        - PhD-practical/perks-of-the-phd.md
        - PhD-practical/choosing-a-thematic-programme.md                
    - Software and hardware:
        - software-hardware/CECI-and-other-clusters.md
        - software-hardware/software-microsoft-office-license.md
        - software-hardware/bioconda.md
        - software-hardware/docker.md
        - software-hardware/singularity.md
        - software-hardware/tempest.md
    - Scientific good practises:
        - tip_and_tricks/how-to-write-a-paper.md
        - tip_and_tricks/colors.md
        - tip_and_tricks/phd-postdoc-society.md
    - Phylogenetics: 
        - phylogenetics/intro-to-phylogenetics.md

theme:
    name: material
    font:
        text: Merriweather Sans
        code: Red Hat Mono
    # favicon: image that appears in tab    
    favicon: images/spell-logo_grey_noText.png
    logo: images/spell-logo_grey_noText.png
    palette:
#        # system preference
#        - media: "(prefers-color-scheme)"
#          toggle:
#              icon: material/brightness-auto
#              name: Switch to light mode
        # light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        # dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
              icon: material/weather-night
              name: Switch to system preference
    font:
        text: "Lora"
        code: "Ubuntu Mono"    
    features:
        - announce.dismiss
        - content.action.edit
        - content.code.annotate
        - content.code.copy
        #- navigation.sections
        - navigation.prune
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - search.share
        - search.suggest
        - search.highlight
        - toc.follow
        - content.footnote.tooltips
        #- navigation.footer

extra_css:
    - stylesheets/extra.css
    - https://unpkg.com/leaflet@1.3.1/dist/leaflet.css
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css

extra_javascript:
    - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
    - js/map-renderer.js

markdown_extensions:
    # highlights of text in boxes (tripple !!! of ???)
    - admonition
    - attr_list
    - def_list
    - tables
    - md_in_html
    - footnotes
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.critic
    - pymdownx.snippets
    # for diagrams: 
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.details
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.arithmatex:
          generic: true

plugins:
    - search
    - git-authors:
          show_contribution: true
          sort_authors_by: contribution
          ignore_authors:
              - 61584065+joon-klaps@users.noreply.github.com
          exclude:
              - index.md
    - git-revision-date-localized:
          type: timeago
    - awesome-pages

extra:
    homepage: https://spell.ulb.be/
    generator: false
    social:
        #- icon: fontawesome/brands/x-twitter
        #  link: https://twitter.com/LemeyLab
        - icon: fontawesome/brands/github
          link: https://github.com/bramvrancken
